export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_AVERAGE = "GET_AVERAGE";
